package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWxCashInfo<M extends BaseWxCashInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setBasicId(java.lang.Integer basicId) {
		set("basic_id", basicId);
		return (M)this;
	}
	
	public java.lang.Integer getBasicId() {
		return getInt("basic_id");
	}

	public M setDetailId(java.lang.Integer detailId) {
		set("detail_id", detailId);
		return (M)this;
	}
	
	public java.lang.Integer getDetailId() {
		return getInt("detail_id");
	}

	public M setDealPrice(java.lang.Integer dealPrice) {
		set("deal_price", dealPrice);
		return (M)this;
	}
	
	public java.lang.Integer getDealPrice() {
		return getInt("deal_price");
	}

	public M setDesc(java.lang.String desc) {
		set("desc", desc);
		return (M)this;
	}
	
	public java.lang.String getDesc() {
		return getStr("desc");
	}

	public M setResult(java.lang.String result) {
		set("result", result);
		return (M)this;
	}
	
	public java.lang.String getResult() {
		return getStr("result");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
