package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderBasic<M extends BaseOrderBasic<M>> extends Model<M> implements IBean {

	public M setOId(java.lang.Integer oId) {
		set("o_id", oId);
		return (M)this;
	}
	
	public java.lang.Integer getOId() {
		return getInt("o_id");
	}

	public M setSId(java.lang.Integer sId) {
		set("s_id", sId);
		return (M)this;
	}
	
	public java.lang.Integer getSId() {
		return getInt("s_id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
		return (M)this;
	}
	
	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	public M setTotalPrice(java.math.BigDecimal totalPrice) {
		set("total_price", totalPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalPrice() {
		return get("total_price");
	}

	public M setConsigneeName(java.lang.String consigneeName) {
		set("consignee_name", consigneeName);
		return (M)this;
	}
	
	public java.lang.String getConsigneeName() {
		return getStr("consignee_name");
	}

	public M setConsigneePhone(java.lang.String consigneePhone) {
		set("consignee_phone", consigneePhone);
		return (M)this;
	}
	
	public java.lang.String getConsigneePhone() {
		return getStr("consignee_phone");
	}

	public M setConsigneeAddress(java.lang.String consigneeAddress) {
		set("consignee_address", consigneeAddress);
		return (M)this;
	}
	
	public java.lang.String getConsigneeAddress() {
		return getStr("consignee_address");
	}

	public M setConsigneeRangeTime(java.lang.String consigneeRangeTime) {
		set("consignee_range_time", consigneeRangeTime);
		return (M)this;
	}
	
	public java.lang.String getConsigneeRangeTime() {
		return getStr("consignee_range_time");
	}

	public M setPaymentStatus(java.lang.Integer paymentStatus) {
		set("payment_status", paymentStatus);
		return (M)this;
	}
	
	public java.lang.Integer getPaymentStatus() {
		return getInt("payment_status");
	}

	public M setPaymentChannel(java.lang.Integer paymentChannel) {
		set("payment_channel", paymentChannel);
		return (M)this;
	}
	
	public java.lang.Integer getPaymentChannel() {
		return getInt("payment_channel");
	}

	public M setPostCost(java.math.BigDecimal postCost) {
		set("post_cost", postCost);
		return (M)this;
	}
	
	public java.math.BigDecimal getPostCost() {
		return get("post_cost");
	}

	public M setOutTradeNo(java.lang.String outTradeNo) {
		set("out_trade_no", outTradeNo);
		return (M)this;
	}
	
	public java.lang.String getOutTradeNo() {
		return getStr("out_trade_no");
	}

	public M setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
		return (M)this;
	}
	
	public java.lang.String getTransactionId() {
		return getStr("transaction_id");
	}

	public M setBackPriceStatus(java.lang.Integer backPriceStatus) {
		set("back_price_status", backPriceStatus);
		return (M)this;
	}
	
	public java.lang.Integer getBackPriceStatus() {
		return getInt("back_price_status");
	}

	public M setIsExpress(java.lang.Integer isExpress) {
		set("is_express", isExpress);
		return (M)this;
	}
	
	public java.lang.Integer getIsExpress() {
		return getInt("is_express");
	}

	public M setExpressType(java.lang.String expressType) {
		set("express_type", expressType);
		return (M)this;
	}
	
	public java.lang.String getExpressType() {
		return getStr("express_type");
	}

	public M setExpressNo(java.lang.String expressNo) {
		set("express_no", expressNo);
		return (M)this;
	}
	
	public java.lang.String getExpressNo() {
		return getStr("express_no");
	}

	public M setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}
	
	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	public M setLastTime(java.util.Date lastTime) {
		set("last_time", lastTime);
		return (M)this;
	}
	
	public java.util.Date getLastTime() {
		return get("last_time");
	}

	public M setExtraPayment(java.math.BigDecimal extraPayment) {
		set("extra_payment", extraPayment);
		return (M)this;
	}
	
	public java.math.BigDecimal getExtraPayment() {
		return get("extra_payment");
	}

	public M setExtraTime(java.util.Date extraTime) {
		set("extra_time", extraTime);
		return (M)this;
	}
	
	public java.util.Date getExtraTime() {
		return get("extra_time");
	}

	public M setExtraStatus(java.lang.Integer extraStatus) {
		set("extra_status", extraStatus);
		return (M)this;
	}
	
	public java.lang.Integer getExtraStatus() {
		return getInt("extra_status");
	}

	public M setExtraChannel(java.lang.Integer extraChannel) {
		set("extra_channel", extraChannel);
		return (M)this;
	}
	
	public java.lang.Integer getExtraChannel() {
		return getInt("extra_channel");
	}

	public M setExtraOutTradeNo(java.lang.String extraOutTradeNo) {
		set("extra_out_trade_no", extraOutTradeNo);
		return (M)this;
	}
	
	public java.lang.String getExtraOutTradeNo() {
		return getStr("extra_out_trade_no");
	}

	public M setExtraTransactionId(java.lang.String extraTransactionId) {
		set("extra_transaction_id", extraTransactionId);
		return (M)this;
	}
	
	public java.lang.String getExtraTransactionId() {
		return getStr("extra_transaction_id");
	}

	public M setTotalBackPrice(java.math.BigDecimal totalBackPrice) {
		set("total_back_price", totalBackPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getTotalBackPrice() {
		return get("total_back_price");
	}

	public M setBackRefundId(java.lang.String backRefundId) {
		set("back_refund_id", backRefundId);
		return (M)this;
	}
	
	public java.lang.String getBackRefundId() {
		return getStr("back_refund_id");
	}

	public M setBackOutRefundNo(java.lang.String backOutRefundNo) {
		set("back_out_refund_no", backOutRefundNo);
		return (M)this;
	}
	
	public java.lang.String getBackOutRefundNo() {
		return getStr("back_out_refund_no");
	}

}
