package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGlobalConf<M extends BaseGlobalConf<M>> extends Model<M> implements IBean {

	public M setCId(java.lang.Integer cId) {
		set("c_id", cId);
		return (M)this;
	}
	
	public java.lang.Integer getCId() {
		return getInt("c_id");
	}

	public M setCType(java.lang.Integer cType) {
		set("c_type", cType);
		return (M)this;
	}
	
	public java.lang.Integer getCType() {
		return getInt("c_type");
	}

	public M setCTime(java.lang.String cTime) {
		set("c_time", cTime);
		return (M)this;
	}
	
	public java.lang.String getCTime() {
		return getStr("c_time");
	}

	public M setCAppid(java.lang.String cAppid) {
		set("c_appid", cAppid);
		return (M)this;
	}
	
	public java.lang.String getCAppid() {
		return getStr("c_appid");
	}

	public M setCSecret(java.lang.String cSecret) {
		set("c_secret", cSecret);
		return (M)this;
	}
	
	public java.lang.String getCSecret() {
		return getStr("c_secret");
	}

	public M setApiSecuret(java.lang.String apiSecuret) {
		set("API_SECURET", apiSecuret);
		return (M)this;
	}
	
	public java.lang.String getApiSecuret() {
		return getStr("API_SECURET");
	}

}
