package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAddressInfo<M extends BaseAddressInfo<M>> extends Model<M> implements IBean {

	public M setAId(java.lang.Integer aId) {
		set("a_id", aId);
		return (M)this;
	}
	
	public java.lang.Integer getAId() {
		return getInt("a_id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setACity(java.lang.String aCity) {
		set("a_city", aCity);
		return (M)this;
	}
	
	public java.lang.String getACity() {
		return getStr("a_city");
	}

	public M setADetail(java.lang.String aDetail) {
		set("a_detail", aDetail);
		return (M)this;
	}
	
	public java.lang.String getADetail() {
		return getStr("a_detail");
	}

	public M setLatitude(java.lang.String latitude) {
		set("latitude", latitude);
		return (M)this;
	}
	
	public java.lang.String getLatitude() {
		return getStr("latitude");
	}

	public M setLongitude(java.lang.String longitude) {
		set("longitude", longitude);
		return (M)this;
	}
	
	public java.lang.String getLongitude() {
		return getStr("longitude");
	}

	public M setDistance(java.lang.String distance) {
		set("distance", distance);
		return (M)this;
	}
	
	public java.lang.String getDistance() {
		return getStr("distance");
	}

	public M setIsUsed(java.lang.Integer isUsed) {
		set("is_used", isUsed);
		return (M)this;
	}
	
	public java.lang.Integer getIsUsed() {
		return getInt("is_used");
	}

}
