package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAddressInfo<M extends BaseAddressInfo<M>> extends Model<M> implements IBean {

	public M setAId(java.lang.Integer aId) {
		set("a_id", aId);
		return (M)this;
	}
	
	public java.lang.Integer getAId() {
		return getInt("a_id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setAProvince(java.lang.String aProvince) {
		set("a_province", aProvince);
		return (M)this;
	}
	
	public java.lang.String getAProvince() {
		return getStr("a_province");
	}

	public M setACity(java.lang.String aCity) {
		set("a_city", aCity);
		return (M)this;
	}
	
	public java.lang.String getACity() {
		return getStr("a_city");
	}

	public M setADistrict(java.lang.String aDistrict) {
		set("a_district", aDistrict);
		return (M)this;
	}
	
	public java.lang.String getADistrict() {
		return getStr("a_district");
	}

	public M setAAdcode(java.lang.String aAdcode) {
		set("a_adcode", aAdcode);
		return (M)this;
	}
	
	public java.lang.String getAAdcode() {
		return getStr("a_adcode");
	}

	public M setAStreet(java.lang.String aStreet) {
		set("a_street", aStreet);
		return (M)this;
	}
	
	public java.lang.String getAStreet() {
		return getStr("a_street");
	}

	public M setADetail(java.lang.String aDetail) {
		set("a_detail", aDetail);
		return (M)this;
	}
	
	public java.lang.String getADetail() {
		return getStr("a_detail");
	}

	public M setIsUsed(java.lang.Integer isUsed) {
		set("is_used", isUsed);
		return (M)this;
	}
	
	public java.lang.Integer getIsUsed() {
		return getInt("is_used");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

}
