package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUserSetting<M extends BaseUserSetting<M>> extends Model<M> implements IBean {

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setUAccount(java.lang.String uAccount) {
		set("u_account", uAccount);
		return (M)this;
	}
	
	public java.lang.String getUAccount() {
		return getStr("u_account");
	}

	public M setUPwd(java.lang.String uPwd) {
		set("u_pwd", uPwd);
		return (M)this;
	}
	
	public java.lang.String getUPwd() {
		return getStr("u_pwd");
	}

	public M setUNickName(java.lang.String uNickName) {
		set("u_nick_name", uNickName);
		return (M)this;
	}
	
	public java.lang.String getUNickName() {
		return getStr("u_nick_name");
	}

	public M setUPhone(java.lang.String uPhone) {
		set("u_phone", uPhone);
		return (M)this;
	}
	
	public java.lang.String getUPhone() {
		return getStr("u_phone");
	}

	public M setUCode(java.lang.String uCode) {
		set("u_code", uCode);
		return (M)this;
	}
	
	public java.lang.String getUCode() {
		return getStr("u_code");
	}

	public M setUAvatarUrl(java.lang.String uAvatarUrl) {
		set("u_avatar_url", uAvatarUrl);
		return (M)this;
	}
	
	public java.lang.String getUAvatarUrl() {
		return getStr("u_avatar_url");
	}

	public M setAccountPrice(java.math.BigDecimal accountPrice) {
		set("account_price", accountPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getAccountPrice() {
		return get("account_price");
	}

	public M setUPlot(java.lang.String uPlot) {
		set("u_plot", uPlot);
		return (M)this;
	}
	
	public java.lang.String getUPlot() {
		return getStr("u_plot");
	}

	public M setUContent(java.lang.String uContent) {
		set("u_content", uContent);
		return (M)this;
	}
	
	public java.lang.String getUContent() {
		return getStr("u_content");
	}

	public M setULastTime(java.util.Date uLastTime) {
		set("u_last_time", uLastTime);
		return (M)this;
	}
	
	public java.util.Date getULastTime() {
		return get("u_last_time");
	}

	public M setULogout(java.lang.Integer uLogout) {
		set("u_logout", uLogout);
		return (M)this;
	}
	
	public java.lang.Integer getULogout() {
		return getInt("u_logout");
	}

	public M setUConcern(java.lang.Integer uConcern) {
		set("u_concern", uConcern);
		return (M)this;
	}
	
	public java.lang.Integer getUConcern() {
		return getInt("u_concern");
	}

	public M setUFans(java.lang.Integer uFans) {
		set("u_fans", uFans);
		return (M)this;
	}
	
	public java.lang.Integer getUFans() {
		return getInt("u_fans");
	}

	public M setULiked(java.lang.Integer uLiked) {
		set("u_liked", uLiked);
		return (M)this;
	}
	
	public java.lang.Integer getULiked() {
		return getInt("u_liked");
	}

	public M setUOpenid(java.lang.String uOpenid) {
		set("u_openid", uOpenid);
		return (M)this;
	}
	
	public java.lang.String getUOpenid() {
		return getStr("u_openid");
	}

}
