package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotissueReply<M extends BaseHotissueReply<M>> extends Model<M> implements IBean {

	public M setRId(java.lang.Integer rId) {
		set("r_id", rId);
		return (M)this;
	}
	
	public java.lang.Integer getRId() {
		return getInt("r_id");
	}

	public M setDId(java.lang.Integer dId) {
		set("d_id", dId);
		return (M)this;
	}
	
	public java.lang.Integer getDId() {
		return getInt("d_id");
	}

	public M setRReplyId(java.lang.Integer rReplyId) {
		set("r_reply_id", rReplyId);
		return (M)this;
	}
	
	public java.lang.Integer getRReplyId() {
		return getInt("r_reply_id");
	}

	public M setRContent(java.lang.String rContent) {
		set("r_content", rContent);
		return (M)this;
	}
	
	public java.lang.String getRContent() {
		return getStr("r_content");
	}

	public M setRDatetime(java.util.Date rDatetime) {
		set("r_datetime", rDatetime);
		return (M)this;
	}
	
	public java.util.Date getRDatetime() {
		return get("r_datetime");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

}
