package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotissueLiked<M extends BaseHotissueLiked<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setLId(java.lang.Integer lId) {
		set("l_id", lId);
		return (M)this;
	}
	
	public java.lang.Integer getLId() {
		return getInt("l_id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

}
