package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHotissueBasic<M extends BaseHotissueBasic<M>> extends Model<M> implements IBean {

	public M setHId(java.lang.Integer hId) {
		set("h_id", hId);
		return (M)this;
	}
	
	public java.lang.Integer getHId() {
		return getInt("h_id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setUPlot(java.lang.String uPlot) {
		set("u_plot", uPlot);
		return (M)this;
	}
	
	public java.lang.String getUPlot() {
		return getStr("u_plot");
	}

	public M setHDatetime(java.util.Date hDatetime) {
		set("h_datetime", hDatetime);
		return (M)this;
	}
	
	public java.util.Date getHDatetime() {
		return get("h_datetime");
	}

	public M setHContext(java.lang.String hContext) {
		set("h_context", hContext);
		return (M)this;
	}
	
	public java.lang.String getHContext() {
		return getStr("h_context");
	}

	public M setHAddressImg(java.lang.String hAddressImg) {
		set("h_address_img", hAddressImg);
		return (M)this;
	}
	
	public java.lang.String getHAddressImg() {
		return getStr("h_address_img");
	}

	public M setHAddressVideo(java.lang.String hAddressVideo) {
		set("h_address_video", hAddressVideo);
		return (M)this;
	}
	
	public java.lang.String getHAddressVideo() {
		return getStr("h_address_video");
	}

	public M setHAppreciateNo(java.lang.Integer hAppreciateNo) {
		set("h_appreciate_no", hAppreciateNo);
		return (M)this;
	}
	
	public java.lang.Integer getHAppreciateNo() {
		return getInt("h_appreciate_no");
	}

	public M setHDiscussNo(java.lang.Integer hDiscussNo) {
		set("h_discuss_no", hDiscussNo);
		return (M)this;
	}
	
	public java.lang.Integer getHDiscussNo() {
		return getInt("h_discuss_no");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
