package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFeedbackInfo<M extends BaseFeedbackInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setOId(java.lang.Integer oId) {
		set("o_id", oId);
		return (M)this;
	}
	
	public java.lang.Integer getOId() {
		return getInt("o_id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setImgUrl(java.lang.String imgUrl) {
		set("img_url", imgUrl);
		return (M)this;
	}
	
	public java.lang.String getImgUrl() {
		return getStr("img_url");
	}

	public M setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
		return (M)this;
	}
	
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setReplay(java.lang.String replay) {
		set("replay", replay);
		return (M)this;
	}
	
	public java.lang.String getReplay() {
		return getStr("replay");
	}

	public M setReplayTime(java.util.Date replayTime) {
		set("replay_time", replayTime);
		return (M)this;
	}
	
	public java.util.Date getReplayTime() {
		return get("replay_time");
	}

}
