package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommodityInfo<M extends BaseCommodityInfo<M>> extends Model<M> implements IBean {

	public M setSId(java.lang.Integer sId) {
		set("s_id", sId);
		return (M)this;
	}
	
	public java.lang.Integer getSId() {
		return getInt("s_id");
	}

	public M setPId(java.lang.Integer pId) {
		set("p_id", pId);
		return (M)this;
	}
	
	public java.lang.Integer getPId() {
		return getInt("p_id");
	}

	public M setTId(java.lang.Integer tId) {
		set("t_id", tId);
		return (M)this;
	}
	
	public java.lang.Integer getTId() {
		return getInt("t_id");
	}

	public M setSName(java.lang.String sName) {
		set("s_name", sName);
		return (M)this;
	}
	
	public java.lang.String getSName() {
		return getStr("s_name");
	}

	public M setSPrice(java.math.BigDecimal sPrice) {
		set("s_price", sPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getSPrice() {
		return get("s_price");
	}

	public M setSUnit(java.lang.String sUnit) {
		set("s_unit", sUnit);
		return (M)this;
	}
	
	public java.lang.String getSUnit() {
		return getStr("s_unit");
	}

	public M setPriceUnit(java.math.BigDecimal priceUnit) {
		set("price_unit", priceUnit);
		return (M)this;
	}
	
	public java.math.BigDecimal getPriceUnit() {
		return get("price_unit");
	}

	public M setInitNum(java.lang.Integer initNum) {
		set("init_num", initNum);
		return (M)this;
	}
	
	public java.lang.Integer getInitNum() {
		return getInt("init_num");
	}

	public M setInitUnit(java.lang.Integer initUnit) {
		set("init_unit", initUnit);
		return (M)this;
	}
	
	public java.lang.Integer getInitUnit() {
		return getInt("init_unit");
	}

	public M setSDesc(java.lang.String sDesc) {
		set("s_desc", sDesc);
		return (M)this;
	}
	
	public java.lang.String getSDesc() {
		return getStr("s_desc");
	}

	public M setSalesDesc(java.lang.String salesDesc) {
		set("sales_desc", salesDesc);
		return (M)this;
	}
	
	public java.lang.String getSalesDesc() {
		return getStr("sales_desc");
	}

	public M setSAddressImg(java.lang.String sAddressImg) {
		set("s_address_img", sAddressImg);
		return (M)this;
	}
	
	public java.lang.String getSAddressImg() {
		return getStr("s_address_img");
	}

	public M setSAddressVideo(java.lang.String sAddressVideo) {
		set("s_address_video", sAddressVideo);
		return (M)this;
	}
	
	public java.lang.String getSAddressVideo() {
		return getStr("s_address_video");
	}

	public M setSSource(java.lang.Integer sSource) {
		set("s_source", sSource);
		return (M)this;
	}
	
	public java.lang.Integer getSSource() {
		return getInt("s_source");
	}

	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public M setIsActive(java.lang.Integer isActive) {
		set("is_active", isActive);
		return (M)this;
	}
	
	public java.lang.Integer getIsActive() {
		return getInt("is_active");
	}

	public M setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
