package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCustomerService<M extends BaseCustomerService<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setQuestionDesc(byte[] questionDesc) {
		set("question_desc", questionDesc);
		return (M)this;
	}
	
	public byte[] getQuestionDesc() {
		return get("question_desc");
	}

	public M setFileUrl(java.lang.String fileUrl) {
		set("file_url", fileUrl);
		return (M)this;
	}
	
	public java.lang.String getFileUrl() {
		return getStr("file_url");
	}

	public M setQuestionReply(java.lang.String questionReply) {
		set("question_reply", questionReply);
		return (M)this;
	}
	
	public java.lang.String getQuestionReply() {
		return getStr("question_reply");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
