package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCommodityTypeSetting<M extends BaseCommodityTypeSetting<M>> extends Model<M> implements IBean {

	public M setTId(java.lang.Integer tId) {
		set("t_id", tId);
		return (M)this;
	}
	
	public java.lang.Integer getTId() {
		return getInt("t_id");
	}

	public M setSId(java.lang.Integer sId) {
		set("s_id", sId);
		return (M)this;
	}
	
	public java.lang.Integer getSId() {
		return getInt("s_id");
	}

	public M setTType(java.lang.Integer tType) {
		set("t_type", tType);
		return (M)this;
	}
	
	public java.lang.Integer getTType() {
		return getInt("t_type");
	}

	public M setTName(java.lang.String tName) {
		set("t_name", tName);
		return (M)this;
	}
	
	public java.lang.String getTName() {
		return getStr("t_name");
	}

	public M setIsPopular(java.lang.Long isPopular) {
		set("is_popular", isPopular);
		return (M)this;
	}
	
	public java.lang.Long getIsPopular() {
		return getLong("is_popular");
	}

	public M setTOff(java.lang.Integer tOff) {
		set("t_off", tOff);
		return (M)this;
	}
	
	public java.lang.Integer getTOff() {
		return getInt("t_off");
	}

}
