package com.cos.cmtgp.business.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShoppingInfo<M extends BaseShoppingInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUId(java.lang.Integer uId) {
		set("u_id", uId);
		return (M)this;
	}
	
	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public M setSId(java.lang.Integer sId) {
		set("s_id", sId);
		return (M)this;
	}
	
	public java.lang.Integer getSId() {
		return getInt("s_id");
	}

	public M setSNum(java.lang.Integer sNum) {
		set("s_num", sNum);
		return (M)this;
	}
	
	public java.lang.Integer getSNum() {
		return getInt("s_num");
	}

	public M setDateTime(java.util.Date dateTime) {
		set("date_time", dateTime);
		return (M)this;
	}
	
	public java.util.Date getDateTime() {
		return get("date_time");
	}

	public M setIsCheck(java.lang.Integer isCheck) {
		set("is_check", isCheck);
		return (M)this;
	}
	
	public java.lang.Integer getIsCheck() {
		return getInt("is_check");
	}

}
