package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseAddressInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AddressInfo extends BaseAddressInfo<AddressInfo> {
	public static final AddressInfo dao = new AddressInfo().dao();
}
