package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseCommodityInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommodityInfo extends BaseCommodityInfo<CommodityInfo> {
	public static final CommodityInfo dao = new CommodityInfo().dao();
}
