package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseCommodityTypeSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CommodityTypeSetting extends BaseCommodityTypeSetting<CommodityTypeSetting> {
	public static final CommodityTypeSetting dao = new CommodityTypeSetting().dao();
}
