package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseCustomerService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerService extends BaseCustomerService<CustomerService> {
	public static final CustomerService dao = new CustomerService().dao();
}
