package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseFeedbackInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FeedbackInfo extends BaseFeedbackInfo<FeedbackInfo> {
	public static final FeedbackInfo dao = new FeedbackInfo().dao();
}
