package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseGlobalConf;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GlobalConf extends BaseGlobalConf<GlobalConf> {
	public static final GlobalConf dao = new GlobalConf().dao();
}
