package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseHotissueBasic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotissueBasic extends BaseHotissueBasic<HotissueBasic> {
	public static final HotissueBasic dao = new HotissueBasic().dao();
}
