package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseHotissueDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotissueDetail extends BaseHotissueDetail<HotissueDetail> {
	public static final HotissueDetail dao = new HotissueDetail().dao();
}
