package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseHotissueReply;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotissueReply extends BaseHotissueReply<HotissueReply> {
	public static final HotissueReply dao = new HotissueReply().dao();
}
