package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseHotissueLiked;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HotissueLiked extends BaseHotissueLiked<HotissueLiked> {
	public static final HotissueLiked dao = new HotissueLiked().dao();
}
