package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseInterfaceInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InterfaceInfo extends BaseInterfaceInfo<InterfaceInfo> {
	public static final InterfaceInfo dao = new InterfaceInfo().dao();
}
