package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetail extends BaseOrderDetail<OrderDetail> {
	public static final OrderDetail dao = new OrderDetail().dao();
}
