package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseOrderBasic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderBasic extends BaseOrderBasic<OrderBasic> {
	public static final OrderBasic dao = new OrderBasic().dao();
}
