package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseShoppingInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShoppingInfo extends BaseShoppingInfo<ShoppingInfo> {
	public static final ShoppingInfo dao = new ShoppingInfo().dao();
}
