package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseSupplierSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplierSetting extends BaseSupplierSetting<SupplierSetting> {
	public static final SupplierSetting dao = new SupplierSetting().dao();
}
