package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseUserSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserSetting extends BaseUserSetting<UserSetting> {
	public static final UserSetting dao = new UserSetting().dao();
}
