package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseUserRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRelation extends BaseUserRelation<UserRelation> {
	public static final UserRelation dao = new UserRelation().dao();
}
