package com.cos.cmtgp.business.model;

import com.cos.cmtgp.business.model.base.BaseWxCashInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxCashInfo extends BaseWxCashInfo<WxCashInfo> {
	public static final WxCashInfo dao = new WxCashInfo().dao();
}
